spring.application.name=tfg_redsocial

# ================================================
# POSTGRESQL DATABASE
# ================================================
spring.datasource.url=jdbc:postgresql://localhost:5432/social_tfg_db
spring.datasource.username=postgres
spring.datasource.password=mysql9669.
spring.datasource.driver-class-name=org.postgresql.Driver

# ================================================
# JPA / HIBERNATE
# ================================================
# Estrategia: update (crea/actualiza tablas automáticamente)
# Para producción usa: validate
spring.jpa.hibernate.ddl-auto=update

# Mostrar SQL en consola (útil para debug)
spring.jpa.show-sql=true
spring.jpa.properties.hibernate.format_sql=true

# Dialecto de PostgreSQL
spring.jpa.properties.hibernate.dialect=org.hibernate.dialect.PostgreSQLDialect

# ================================================
# SERVER
# ================================================
server.port=8080
server.error.include-message=always


# ================================================
# JWT
# ================================================
# Clave secreta para firmar los tokens.
# En producción esto irá en una variable de entorno,
# nunca en texto plano en el código.
jwt.secret=prometeo-tfg-redsocial-clave-secreta-muy-larga-2024-cambiar-en-produccion
jwt.expiration=86400000
# 86400000 ms = 24 horas, como defino en mis requisitos no funcionales
